# https://taskfile.dev

version: "3"

dotenv: [".env"]

vars:
  GREETING: Hello, World!
  PORT: 8000
  CONFIG_PATH: configs/dev.yaml

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run:
    desc: Run the API server
    cmds:
      - go mod tidy
      - go run main.go --port {{.PORT}} --config {{.CONFIG_PATH}}

  "test:e2e":
    desc: Run end-to-end tests
    cmds:
      - scenarigo run tests/e2e/*.yaml

  "lint:openapi":
    desc: Lint OpenAPI specification
    cmds:
      - npx @redocly/cli@latest lint static/openapi.yaml
