# https://taskfile.dev

version: "3"

dotenv: [".env"]

vars:
  GREETING: Hello, World!
  PORT: 8080

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run:
    desc: Run the API server
    cmds:
      - go mod tidy
      - go run main.go --port {{.PORT}}

  "test:e2e":
    desc: Run end-to-end tests
    cmds:
      - scenarigo run tests/e2e/*.yaml
